name: 'dbt_azure_postgresql'
version: '1.0.0'

profile: 'dbt_azure_postgresql'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_azure_postgresql:
    power:
      pjm:
        +schema: pjm_cleaned_v3_2026_04_22
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: ephemeral
