name: 'dbt_azure_postgresql'
version: '1.0.0'

profile: 'dbt_azure_postgresql'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_azure_postgresql:
    +schema: pjm_da_modelling_cleaned
    +materialized: ephemeral
    
    power:
      pjm:
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: ephemeral

    meteologica:
      pjm:
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: ephemeral

    ice_python:
      source:
        +materialized: ephemeral
      staging:
        +materialized: ephemeral
      marts:
        +materialized: ephemeral

    wsi:
      source:
        +materialized: ephemeral
      staging:
        +materialized: ephemeral
      marts:
        +materialized: ephemeral
